# Generated by Django 3.1.4 on 2020-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalunimodel',
            name='welcome_message',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
