# Generated by Django 3.1.4 on 2020-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201218_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalunimodel',
            name='welcome_message',
            field=models.TextField(db_index=True),
        ),
    ]
