# Generated by Django 3.1.4 on 2020-12-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20201218_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUniModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_types', models.CharField(blank=True, choices=[('student', 'Студент'), ('teacher', 'Преподователь'), ('managment', 'Дирекция'), ('admin', 'Админинстратор')], default='student', max_length=150)),
                ('position_manager', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('curatorship', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('chair', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('course', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], db_index=True, default=0)),
                ('group', models.CharField(blank=True, db_index=True, default='', max_length=150)),
                ('full_name', models.CharField(db_index=True, default='', max_length=150)),
                ('phone_number', models.CharField(db_index=True, max_length=50)),
                ('telegram_id', models.CharField(db_index=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
