# Generated by Django 3.1.4 on 2020-12-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_userunimodel_telegram_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralUniModel',
        ),
    ]
