# Generated by Django 3.1.4 on 2020-12-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_delete_generalunimodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userunimodel',
            name='telegram_data',
        ),
    ]
