# Generated by Django 3.1.4 on 2020-12-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_userunimodel_telegram_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunimodel',
            name='user_types',
            field=models.CharField(blank=True, choices=[('student', 'Студент'), ('teacher', 'Преподователь'), ('manager', 'Дирекция'), ('admin', 'Админинстратор')], default='student', max_length=150),
        ),
    ]
