# Generated by Django 3.1.4 on 2020-12-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20201226_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userunimodel',
            name='user_types',
            field=models.CharField(blank=True, choices=[('student', 'Студент'), ('teacher', 'Викладач'), ('manager', 'Дирекція'), ('admin', 'Адміністратор')], default='student', max_length=150),
        ),
    ]
